# site settings
title: Ashish Rao 
subtitle: The Man, The Legend... 
email: ashish.rao.m@gmail.com
description: Hi there! This site demonstrates my work and my interests. Feel free to get in touch with me if you feel like having a conversation. 
baseurl: "/ashish-rao" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ashish Rao Mangalore
street_address: 
city: Bengaluru
state: KA
country: India
phone: <i> Available on Request </i>

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/rao_art
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/ashish-rao-mangalore-4a888a26/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
